### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by mcintyre321** [Lokad/AzureEventStore#1]
This project looks neat. Are you going to release a nuget package for it? I'd like to give it a spin!

**Comment by vermorel** [comment]
@mcintyre321 Yes, a nuget package is part of the plan!

**Comment by VictorNicollet** [comment]
The NuGet package has now been published, as [Lokad.AzureEventStore](https://www.nuget.org/packages/Lokad.AzureEventStore).
