### ISSUE TITLE
Remove the [DataContract] constraint on events

### ISSUE THREAD

**Issue by thomaseyde** [Lokad/AzureEventStore#8]
From a programmer's perspective, mine at least, decorating my events with `[DataContract]` doesn't add any value. I know this is an event, I will usually put in in a namespace containing the word 'Events', and their names will indicate an event (ie `AccountOpened`).

And the serializer doesn't need it.

Would it be possible to remove the constraint? As a new user of this library, it took me a long time to figure out my mistake. Also because the error message isn't very helpful.

**Comment by vermorel** [comment]
Hello Thomas! Thanks a lot for your feedback. I will circle back this with my team. There might be a reason for enforcing `[DataContract]`, but in any case, I agree that the error message should be more explicit.
