### ISSUE TITLE
Explicit error message for invalid events missing the [DataContract] attribute

### ISSUE THREAD

**Issue by thomaseyde** [Lokad/AzureEventStore#9]
If you forget to decorate the event type with `[DataContract]`, you get the lesser helpful exception message: `System.ArgumentException: Cannot write unknown type '{type}'`.

Not only is the type in question missing, it does not say or hint on what could be wrong. The message itself also looks like something which was supposed to be a string interpolation, but then someone didn't finish it.

Related to #8

**Comment by vermorel** [comment]
Agreed. If we maintain the requirement for the `[DataContract]` attribute, the error message should be fully explicit. We will be looking into this. This is summer, and a lot of the engineering staff of Lokad is on-and-off in vacations, so I might take a while for us to get back to this.

**Comment by VictorNicollet** [comment]
The requirement for `[DataContract]` was dropped.
